version: '3'
services:
    postgres:
        image: 'postgres:latest'       
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
    redis:
        image: 'redis:latest'
    api:
        depends_on:
            - postgres
            - redis
            - worker
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            # - POSTGRES_HOST_AUTH_METHOD=trust
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PORT=5432
    client:
        depends_on:
            - api
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
            - CI=true
    worker:
        depends_on:
            - redis
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        restart: always
        ports:
            - "8080:80"